// This file will be auto-generated by Supabase CLI
// For now, we'll define a basic structure
// Run: npx supabase gen types typescript --project-id YOUR_PROJECT_ID > lib/supabase/database.types.ts

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      districts: {
        Row: {
          id: string; // UUID
          name: string;
          code: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          code?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          code?: string | null;
          created_at?: string;
        };
      };
      profiles: {
        Row: {
          id: string; // UUID
          full_name: string;
          role: 'admin' | 'inspector' | 'accounts' | 'reports';
          district_id: string | null; // UUID
          created_at: string;
        };
        Insert: {
          id: string;
          full_name: string;
          role: 'admin' | 'inspector' | 'accounts' | 'reports';
          district_id?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          full_name?: string;
          role?: 'admin' | 'inspector' | 'accounts' | 'reports';
          district_id?: string | null;
          created_at?: string;
        };
      };
      institutions: {
        Row: {
          id: string; // UUID
          district_id: string; // UUID
          ap_gazette_no: string;
          name: string;
          mandal: string | null;
          village: string | null;
          is_active: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          district_id: string;
          ap_gazette_no: string;
          name: string;
          mandal?: string | null;
          village?: string | null;
          is_active?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          district_id?: string;
          ap_gazette_no?: string;
          name?: string;
          mandal?: string | null;
          village?: string | null;
          is_active?: boolean;
          created_at?: string;
        };
      };
      collections: {
        Row: {
          id: number;
          institution_id: number;
          inspector_id: string;
          arrear_amount: number;
          current_amount: number;
          total_amount: number;
          status: 'pending' | 'sent_to_accounts' | 'verified' | 'rejected';
          collection_date: string;
          challan_no: string | null;
          challan_date: string | null;
          verified_by: string | null;
          verified_at: string | null;
          remarks: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: number;
          institution_id: number;
          inspector_id: string;
          arrear_amount?: number;
          current_amount?: number;
          status?: 'pending' | 'sent_to_accounts' | 'verified' | 'rejected';
          collection_date?: string;
          challan_no?: string | null;
          challan_date?: string | null;
          verified_by?: string | null;
          verified_at?: string | null;
          remarks?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: number;
          institution_id?: number;
          inspector_id?: string;
          arrear_amount?: number;
          current_amount?: number;
          status?: 'pending' | 'sent_to_accounts' | 'verified' | 'rejected';
          collection_date?: string;
          challan_no?: string | null;
          challan_date?: string | null;
          verified_by?: string | null;
          verified_at?: string | null;
          remarks?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      receipts: {
        Row: {
          id: number;
          collection_id: number;
          type: 'bill' | 'transaction';
          file_path: string;
          file_name: string;
          file_size: number | null;
          mime_type: string | null;
          created_at: string;
        };
        Insert: {
          id?: number;
          collection_id: number;
          type: 'bill' | 'transaction';
          file_path: string;
          file_name: string;
          file_size?: number | null;
          mime_type?: string | null;
          created_at?: string;
        };
        Update: {
          id?: number;
          collection_id?: number;
          type?: 'bill' | 'transaction';
          file_path?: string;
          file_name?: string;
          file_size?: number | null;
          mime_type?: string | null;
          created_at?: string;
        };
      };
      audit_log: {
        Row: {
          id: number;
          user_id: string | null;
          action: string;
          table_name: string | null;
          row_id: string | null;
          details: Json | null;
          ip_address: string | null;
          user_agent: string | null;
          created_at: string;
        };
        Insert: {
          id?: number;
          user_id?: string | null;
          action: string;
          table_name?: string | null;
          row_id?: string | null;
          details?: Json | null;
          ip_address?: string | null;
          user_agent?: string | null;
          created_at?: string;
        };
        Update: {
          id?: number;
          user_id?: string | null;
          action?: string;
          table_name?: string | null;
          row_id?: string | null;
          details?: Json | null;
          ip_address?: string | null;
          user_agent?: string | null;
          created_at?: string;
        };
      };
    };
  };
}
